# Generated by Django 5.1.4 on 2026-05-01 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_annually', models.DecimalField(decimal_places=2, max_digits=10)),
                ('setup_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('whm_package_name', models.CharField(blank=True, max_length=100)),
                ('disk_quota_mb', models.PositiveIntegerField(default=0)),
                ('bandwidth_mb', models.PositiveIntegerField(default=0)),
                ('email_accounts', models.PositiveIntegerField(default=0)),
                ('databases', models.PositiveIntegerField(default=0)),
                ('domains_allowed', models.PositiveIntegerField(default=1)),
                ('subdomains_allowed', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('stripe_price_monthly_id', models.CharField(blank=True, max_length=255)),
                ('stripe_price_annually_id', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['sort_order', 'price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='PackageFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=255)),
                ('is_positive', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='products.package')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
