# Generated by Django 5.1.4 on 2026-05-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_quotable',
            field=models.BooleanField(default=False, help_text="Show this package in the public 'Build a quote' catalogue."),
        ),
        migrations.AddField(
            model_name='package',
            name='quote_blurb',
            field=models.TextField(blank=True, help_text='Short marketing description shown on the public quote builder card.'),
        ),
        migrations.AddField(
            model_name='package',
            name='quote_category',
            field=models.CharField(blank=True, help_text='Free-text category label for grouping in the public quote builder (e.g. Hosting, Email, Security).', max_length=50),
        ),
    ]
