# Generated by Django 5.1.4 on 2026-05-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_package_is_quotable_package_quote_blurb_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['card_sort_order', 'sort_order', 'price_monthly']},
        ),
        migrations.AddField(
            model_name='package',
            name='card_badge',
            field=models.CharField(blank=True, help_text='Optional badge text (e.g. Most Popular).', max_length=40),
        ),
        migrations.AddField(
            model_name='package',
            name='card_blurb',
            field=models.CharField(blank=True, help_text='Short subtitle for the homepage package card.', max_length=180),
        ),
        migrations.AddField(
            model_name='package',
            name='card_cta_label',
            field=models.CharField(default='Get Started', max_length=60),
        ),
        migrations.AddField(
            model_name='package',
            name='card_sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='package',
            name='show_on_homepage',
            field=models.BooleanField(default=True, help_text='Show this package card on the public homepage.'),
        ),
    ]
