# Generated by Codex on 2026-05-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_package_options_package_card_badge_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="provisioning_provider",
            field=models.CharField(
                choices=[("whm", "WHM/cPanel"), ("docker_node", "Docker node daemon")],
                default="whm",
                help_text="Default backend used to provision services for this package.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="provisioning_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Provider-specific configuration merged into service provisioning jobs.",
            ),
        ),
    ]
