# Generated by Django 5.1.4 on 2026-05-01 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudflareZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zone_id', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('ssl_mode', models.CharField(default='flexible', max_length=20)),
                ('always_https', models.BooleanField(default=True)),
                ('security_level', models.CharField(default='medium', max_length=20)),
                ('domain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cloudflare_zone', to='domains.domain')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
