# Generated by Django 5.1.4 on 2026-05-04 09:48

import apps.billing.models
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingDocumentBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(default='Grumpy Hosting', max_length=255)),
                ('registered_address', models.TextField(blank=True)),
                ('company_number', models.CharField(blank=True, max_length=64)),
                ('vat_number', models.CharField(blank=True, max_length=64)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('support_phone', models.CharField(blank=True, max_length=64)),
                ('website_url', models.URLField(blank=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to='billing/branding/')),
                ('accent_colour', models.CharField(default='#0ea5e9', help_text='Hex e.g. #0ea5e9', max_length=9)),
                ('header_text', models.TextField(blank=True, help_text='Optional intro text shown above line items')),
                ('footer_text', models.TextField(blank=True, help_text='Shown at the bottom of every page')),
                ('legal_text', models.TextField(blank=True, help_text='Terms / payment terms / legal small print')),
                ('signature_block', models.TextField(blank=True)),
                ('default_currency', models.CharField(default='GBP', max_length=3)),
                ('default_vat_rate', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5)),
                ('default_due_days', models.PositiveSmallIntegerField(default=14)),
                ('default_quote_validity_days', models.PositiveSmallIntegerField(default=30)),
                ('invoice_number_format', models.CharField(default=apps.billing.models._default_invoice_number_format, max_length=64)),
                ('quote_number_format', models.CharField(default=apps.billing.models._default_quote_number_format, max_length=64)),
                ('invoice_seq', models.PositiveIntegerField(default=0)),
                ('quote_seq', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Billing document branding',
                'verbose_name_plural': 'Billing document branding',
            },
        ),
        migrations.AlterModelOptions(
            name='invoicelineitem',
            options={'ordering': ['position', 'id']},
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_by_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='currency',
            field=models.CharField(default='GBP', max_length=3),
        ),
        migrations.AddField(
            model_name='invoice',
            name='source_kind',
            field=models.CharField(choices=[('domain_registration', 'Domain registration'), ('domain_renewal', 'Domain renewal'), ('auto_renewal', 'Auto-renewal'), ('service_order', 'Service order'), ('quote_acceptance', 'Quote acceptance'), ('manual_admin', 'Manual / admin'), ('stripe_subscription', 'Stripe subscription')], default='manual_admin', max_length=32),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='position',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('converted', 'Converted to invoice'), ('void', 'Void')], default='draft', max_length=20)),
                ('lead_email', models.EmailField(blank=True, max_length=254)),
                ('lead_name', models.CharField(blank=True, max_length=255)),
                ('lead_company', models.CharField(blank=True, max_length=255)),
                ('lead_phone', models.CharField(blank=True, max_length=64)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Visible to the customer')),
                ('internal_notes', models.TextField(blank=True, help_text='Staff-only')),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('converted_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originating_quote', to='billing.invoice')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='source_quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_invoices', to='billing.quote'),
        ),
        migrations.CreateModel(
            name='QuoteLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='billing.quote')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
