# Generated by Django 5.1.4 on 2026-05-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_billingdocumentbranding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='last_dunning_sent_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the most recent overdue reminder email sent for this invoice.', null=True),
        ),
    ]
