# Generated by Django 5.1.4 on 2026-05-01 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled'), ('terminated', 'Terminated'), ('failed', 'Failed'), ('review', 'Pending Review')], default='pending', max_length=20)),
                ('domain_name', models.CharField(blank=True, max_length=255)),
                ('cpanel_username', models.CharField(blank=True, max_length=16)),
                ('cpanel_domain', models.CharField(blank=True, max_length=255)),
                ('cpanel_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('cpanel_server', models.CharField(blank=True, max_length=255)),
                ('billing_period', models.CharField(choices=[('monthly', 'Monthly'), ('annually', 'Annually')], default='monthly', max_length=20)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='products.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
    ]
