# Generated by Codex on 2026-05-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_service_whm_sync_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="provisioning_provider",
            field=models.CharField(
                blank=True,
                choices=[("", "Use package default"), ("whm", "WHM/cPanel"), ("docker_node", "Docker node daemon")],
                default="",
                help_text="Optional backend override for this individual service.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="provisioning_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Provider-specific configuration that overrides package provisioning config.",
            ),
        ),
    ]
