# Generated by Django 5.1.4 on 2026-05-01 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('tld', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('transferred', 'Transferred'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('registrar_id', models.CharField(blank=True, max_length=255)),
                ('registered_at', models.DateField(blank=True, null=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('is_locked', models.BooleanField(default=True)),
                ('dns_provider', models.CharField(choices=[('registrar', 'Registrar'), ('cpanel', 'cPanel'), ('cloudflare', 'Cloudflare'), ('external', 'External')], default='registrar', max_length=20)),
                ('cloudflare_zone_id', models.CharField(blank=True, max_length=255)),
                ('nameserver1', models.CharField(blank=True, max_length=255)),
                ('nameserver2', models.CharField(blank=True, max_length=255)),
                ('nameserver3', models.CharField(blank=True, max_length=255)),
                ('nameserver4', models.CharField(blank=True, max_length=255)),
                ('epp_code', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='domains', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
