# Generated by Django 5.1.4 on 2026-05-01 20:01

import apps.domains.models
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('domains', '0003_domaincontact_domainorder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainpricingsettings',
            name='supported_tlds',
            field=models.JSONField(default=apps.domains.models._default_supported_tlds),
        ),
        migrations.CreateModel(
            name='DomainRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('renewal_years', models.PositiveSmallIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending payment'), ('paid', 'Paid'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=20)),
                ('new_expiry_date', models.DateField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renewals', to='domains.domain')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='domain_renewals', to='billing.invoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='domain_renewals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Domain renewal',
                'verbose_name_plural': 'Domain renewals',
                'ordering': ['-created_at'],
            },
        ),
    ]
