# Generated by Django 5.1.4 on 2026-05-04 15:57

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_billingdocumentbranding_and_more'),
        ('domains', '0005_domaincontact_registrant_validation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain_name', models.CharField(max_length=255, unique=True)),
                ('tld', models.CharField(max_length=50)),
                ('auth_code', models.CharField(blank=True, max_length=255)),
                ('quoted_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending payment'), ('paid', 'Paid'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=20)),
                ('auto_renew', models.BooleanField(default=True)),
                ('dns_provider', models.CharField(choices=[('registrar', 'Registrar'), ('cpanel', 'cPanel'), ('cloudflare', 'Cloudflare'), ('external', 'External')], default='cpanel', max_length=20)),
                ('registrar_order_id', models.CharField(blank=True, max_length=255)),
                ('last_error', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin_transfers', to='domains.domaincontact')),
                ('billing_contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_transfers', to='domains.domaincontact')),
                ('domain', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer', to='domains.domain')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='domain_transfers', to='billing.invoice')),
                ('registration_contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registration_transfers', to='domains.domaincontact')),
                ('tech_contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tech_transfers', to='domains.domaincontact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='domain_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Domain transfer',
                'verbose_name_plural': 'Domain transfers',
                'ordering': ['-created_at'],
            },
        ),
    ]
