# Generated by Django 5.1.4 on 2026-05-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_code', models.CharField(choices=[('404', '404 Not Found'), ('500', '500 Server Error')], max_length=3, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('cta_label', models.CharField(default='Back to home', max_length=60)),
                ('cta_url', models.CharField(default='/', max_length=255)),
                ('animation_style', models.CharField(default='float-orbs', max_length=50)),
            ],
            options={
                'verbose_name': 'Error page content',
                'verbose_name_plural': 'Error page content',
            },
        ),
        migrations.CreateModel(
            name='HomeFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Home FAQ',
                'verbose_name_plural': 'Home FAQs',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeServiceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=180)),
                ('description', models.TextField(blank=True)),
                ('icon_emoji', models.CharField(default='⚡', max_length=8)),
                ('cta_label', models.CharField(default='Learn more', max_length=60)),
                ('cta_url', models.CharField(blank=True, max_length=255)),
                ('features', models.TextField(blank=True, help_text='One feature per line')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Home service card',
                'verbose_name_plural': 'Home service cards',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField()),
                ('show_in_footer', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Legal page',
                'verbose_name_plural': 'Legal pages',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SiteContentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_tagline', models.CharField(blank=True, max_length=255)),
                ('footer_about', models.TextField(blank=True)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('support_phone', models.CharField(blank=True, max_length=50)),
                ('enable_cookie_banner', models.BooleanField(default=True)),
                ('cookie_banner_text', models.CharField(default='We use cookies to improve your experience. You can accept or reject non-essential cookies.', max_length=255)),
                ('cookie_policy_slug', models.SlugField(default='cookie-policy')),
            ],
            options={
                'verbose_name': 'Site content settings',
                'verbose_name_plural': 'Site content settings',
            },
        ),
    ]
