# Generated by Django 5.1.4 on 2026-05-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.CharField(choices=[('db', 'Store in database (admin review table)'), ('email', 'Send by email only'), ('both', 'Both — store in DB and send email')], default='db', help_text='Where submitted contact forms are delivered.', max_length=10)),
                ('destination_email', models.EmailField(blank=True, help_text='Required when destination includes email.', max_length=254)),
                ('notify_on_submit', models.BooleanField(default=True, help_text='Send a notification email to destination_email for each submission.')),
                ('form_title', models.CharField(default='Contact Us', help_text='Heading shown on the public contact page.', max_length=120)),
                ('form_intro', models.TextField(blank=True, default="Fill in the form below and we'll get back to you as soon as possible.", help_text='Introductory text above the form.')),
                ('thank_you_message', models.CharField(default="Thank you for getting in touch. We'll be in touch shortly.", help_text='Success message shown after form submission.', max_length=255)),
            ],
            options={
                'verbose_name': 'Contact form settings',
                'verbose_name_plural': 'Contact form settings',
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied'), ('archived', 'Archived')], default='new', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('admin_notes', models.TextField(blank=True, help_text='Staff-only notes on this enquiry.')),
            ],
            options={
                'verbose_name': 'Contact submission',
                'verbose_name_plural': 'Contact submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
