# Generated by Django 5.1.4 on 2026-05-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_blog_post_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('level', models.CharField(choices=[('info', 'Info (blue)'), ('warning', 'Warning (amber)'), ('danger', 'Danger (red)'), ('success', 'Success (green)')], default='info', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('show_to_staff_only', models.BooleanField(default=False)),
                ('url', models.CharField(blank=True, help_text='Optional CTA link.', max_length=500)),
                ('url_label', models.CharField(blank=True, help_text='CTA button label.', max_length=100)),
            ],
            options={
                'verbose_name': 'Announcement banner',
                'verbose_name_plural': 'Announcement banners',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percent', 'Percentage off'), ('fixed', 'Fixed amount off')], default='percent', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage (0–100) or fixed amount.', max_digits=10)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited.', null=True)),
                ('uses', models.PositiveIntegerField(default=0)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Promo code',
                'verbose_name_plural': 'Promo codes',
                'ordering': ['-created_at'],
            },
        ),
    ]
