from django.urls import path
from . import views
from . import wizard_views
from . import billing_views
from . import content_views
from . import operations_views

app_name = "admin_tools"

urlpatterns = [
    # Overview
    path("", views.dashboard, name="dashboard"),
    path("stats/", views.stats, name="stats"),
    # People
    path("users/", views.users, name="users"),
    path("users/new/", content_views.user_create, name="user_create"),
    path("users/<int:pk>/", content_views.user_edit, name="user_edit"),
    path("users/<int:pk>/mfa/", content_views.user_mfa_manage, name="user_mfa_manage"),
    path("users/<int:pk>/su/", content_views.user_su_start, name="user_su_start"),
    path("users/su/stop/", content_views.user_su_stop, name="user_su_stop"),
    path("users/company-lookup/", content_views.company_lookup, name="company_lookup"),
    # Commerce
    path("invoices/", views.invoices, name="invoices"),
    # Billing workbench
    path("billing/branding/", billing_views.branding_edit, name="billing_branding"),
    path("billing/invoices/", billing_views.invoice_list, name="invoice_list"),
    path("billing/invoices/new/", billing_views.invoice_create, name="invoice_create"),
    path("billing/invoices/<int:pk>/", billing_views.invoice_edit, name="invoice_edit"),
    path("billing/invoices/<int:pk>/pdf/", billing_views.invoice_pdf, name="invoice_pdf"),
    path("billing/invoices/<int:pk>/<str:action>/", billing_views.invoice_action, name="invoice_action"),
    path("billing/quotes/", billing_views.quote_list, name="quote_list"),
    path("billing/quotes/new/", billing_views.quote_create, name="quote_create"),
    path("billing/quotes/<int:pk>/", billing_views.quote_edit, name="quote_edit"),
    path("billing/quotes/<int:pk>/pdf/", billing_views.quote_pdf, name="quote_pdf"),
    path("billing/quotes/<int:pk>/<str:action>/", billing_views.quote_action, name="quote_action"),
    path("billing/cart/", billing_views.cart_builder, name="cart_builder"),
    path("billing/cart/add-hosting/", billing_views.cart_builder_add_hosting, name="cart_builder_add_hosting"),
    path("billing/cart/add-domain/", billing_views.cart_builder_add_domain, name="cart_builder_add_domain"),
    path("billing/cart/add-renewal/", billing_views.cart_builder_add_renewal, name="cart_builder_add_renewal"),
    path("billing/cart/add-transfer/", billing_views.cart_builder_add_transfer, name="cart_builder_add_transfer"),
    path("billing/cart/<int:pk>/remove/", billing_views.cart_builder_remove_item, name="cart_builder_remove_item"),
    path("billing/cart/checkout/invoice/", billing_views.cart_builder_checkout_invoice, name="cart_builder_checkout_invoice"),
    path("billing/cart/checkout/quote/", billing_views.cart_builder_checkout_quote, name="cart_builder_checkout_quote"),
    path("domains/pricing/", views.tld_pricing, name="tld_pricing"),
    path("domains/", operations_views.domains_list, name="domains_list"),
    path("domains/new/", operations_views.domains_create, name="domains_create"),
    path("domains/<int:pk>/", operations_views.domains_edit, name="domains_edit"),
    path("domains/<int:pk>/delete/", operations_views.domains_delete, name="domains_delete"),
    path("services/", operations_views.services_list, name="services_list"),
    path("services/new/", operations_views.services_create, name="services_create"),
    path("services/<int:pk>/", operations_views.services_edit, name="services_edit"),
    path("services/<int:pk>/delete/", operations_views.services_delete, name="services_delete"),
    path("support/", operations_views.tickets_list, name="tickets_list"),
    path("support/new/", operations_views.tickets_create, name="tickets_create"),
    path("support/<int:pk>/", operations_views.tickets_edit, name="tickets_edit"),
    path("support/<int:pk>/delete/", operations_views.tickets_delete, name="tickets_delete"),
    path("payments/", operations_views.payments_list, name="payments_list"),
    path("payments/new/", operations_views.payments_create, name="payments_create"),
    path("payments/<int:pk>/", operations_views.payments_edit, name="payments_edit"),
    path("payments/<int:pk>/delete/", operations_views.payments_delete, name="payments_delete"),
    path("templates/", operations_views.templates_list, name="templates_list"),
    path("templates/new/", operations_views.templates_create, name="templates_create"),
    path("templates/<int:pk>/", operations_views.templates_edit, name="templates_edit"),
    path("templates/<int:pk>/delete/", operations_views.templates_delete, name="templates_delete"),
    # Contact submissions
    path("contact/submissions/", operations_views.contact_submissions_list, name="contact_submissions_list"),
    path("contact/submissions/<int:pk>/", operations_views.contact_submission_detail, name="contact_submission_detail"),
    path("contact/submissions/<int:pk>/delete/", operations_views.contact_submission_delete, name="contact_submission_delete"),
    path("contact/config/", operations_views.contact_form_config, name="contact_form_config"),
    # System
    path("tasks/", views.task_management, name="task_management"),
    path("templates/scan/", views.template_scan, name="template_scan"),
    path("integrations/", views.integrations_overview, name="integrations_overview"),
    path("integrations/<str:service>/", views.integration_detail, name="integration_detail"),
    path("integrations/companies-house/config/", views.companies_house_config, name="companies_house_config"),
    path("integrations/resellerclub/debug/", views.resellerclub_debug, name="resellerclub_debug"),
    path("security/", views.security, name="security"),
    path("database/", views.database, name="database"),
    path("settings/", views.settings_overview, name="settings_overview"),
    path("settings/setup/<str:step_key>/", views.settings_setup_step, name="settings_setup_step"),
    path("setup/", views.setup, name="setup"),
    # Setup wizard
    path("setup/wizard/", wizard_views.wizard_index, name="wizard_index"),
    path("setup/wizard/<str:step_key>/", wizard_views.wizard_step, name="wizard_step"),
    path("setup/wizard/reset/", wizard_views.wizard_reset, name="wizard_reset"),
    # Website content CMS
    path("content/", content_views.content_dashboard, name="content_dashboard"),
    path("content/settings/", content_views.content_settings_edit, name="content_settings"),
    path("content/faqs/", content_views.faq_list, name="faq_list"),
    path("content/faqs/new/", content_views.faq_create, name="faq_create"),
    path("content/faqs/<int:pk>/", content_views.faq_edit, name="faq_edit"),
    path("content/faqs/<int:pk>/delete/", content_views.faq_delete, name="faq_delete"),
    path("content/service-cards/", content_views.service_card_list, name="service_card_list"),
    path("content/service-cards/new/", content_views.service_card_create, name="service_card_create"),
    path("content/service-cards/<int:pk>/", content_views.service_card_edit, name="service_card_edit"),
    path("content/service-cards/<int:pk>/delete/", content_views.service_card_delete, name="service_card_delete"),
    path("content/package-cards/", content_views.package_card_list, name="package_card_list"),
    path("content/package-cards/<int:pk>/", content_views.package_card_edit, name="package_card_edit"),
    path("content/legal/", content_views.legal_page_list, name="legal_page_list"),
    path("content/legal/new/", content_views.legal_page_create, name="legal_page_create"),
    path("content/legal/<int:pk>/", content_views.legal_page_edit, name="legal_page_edit"),
    path("content/legal/<int:pk>/delete/", content_views.legal_page_delete, name="legal_page_delete"),
    path("content/errors/", content_views.error_page_list, name="error_page_list"),
    path("content/errors/new/", content_views.error_page_create, name="error_page_create"),
    path("content/errors/<int:pk>/", content_views.error_page_edit, name="error_page_edit"),
    path("content/errors/<int:pk>/delete/", content_views.error_page_delete, name="error_page_delete"),
    # Phase 5: Blog posts
    path("content/blog/", content_views.blog_post_list, name="blog_post_list"),
    path("content/blog/new/", content_views.blog_post_create, name="blog_post_create"),
    path("content/blog/<int:pk>/", content_views.blog_post_edit, name="blog_post_edit"),
    path("content/blog/<int:pk>/delete/", content_views.blog_post_delete, name="blog_post_delete"),
    # Phase 5: Testimonials
    path("content/testimonials/", content_views.testimonial_list, name="testimonial_list"),
    path("content/testimonials/new/", content_views.testimonial_create, name="testimonial_create"),
    path("content/testimonials/<int:pk>/", content_views.testimonial_edit, name="testimonial_edit"),
    path("content/testimonials/<int:pk>/delete/", content_views.testimonial_delete, name="testimonial_delete"),
    # Phase 5: Email template editor
    path("content/email-templates/", content_views.email_template_list, name="email_template_list"),
    path("content/email-templates/<str:name>/", content_views.email_template_edit, name="email_template_edit"),
    path("content/email-templates/<str:name>/delete/", content_views.email_template_delete, name="email_template_delete"),
    # Phase 4: Observability
    path("logs/email/", views.email_log, name="email_log"),
    path("logs/webhooks/", views.webhook_log, name="webhook_log"),
    path("logs/audit/", views.audit_log, name="audit_log"),
    # Phase 5: Feature flags
    path("feature-flags/", views.feature_flags, name="feature_flags"),
    # Phase 7: Promo codes
    path("marketing/promo-codes/", content_views.promo_code_list, name="promo_code_list"),
    path("marketing/promo-codes/new/", content_views.promo_code_create, name="promo_code_create"),
    path("marketing/promo-codes/<int:pk>/", content_views.promo_code_edit, name="promo_code_edit"),
    path("marketing/promo-codes/<int:pk>/delete/", content_views.promo_code_delete, name="promo_code_delete"),
    # Phase 7: Announcement banners
    path("marketing/banners/", content_views.banner_list, name="banner_list"),
    path("marketing/banners/new/", content_views.banner_create, name="banner_create"),
    path("marketing/banners/<int:pk>/", content_views.banner_edit, name="banner_edit"),
    path("marketing/banners/<int:pk>/delete/", content_views.banner_delete, name="banner_delete"),
    # Phase 8: IP allowlist
    path("security/ip-allowlist/", content_views.ip_allowlist, name="ip_allowlist"),
    path("security/ip-allowlist/new/", content_views.ip_allowlist_create, name="ip_allowlist_create"),
    path("security/ip-allowlist/<int:pk>/delete/", content_views.ip_allowlist_delete, name="ip_allowlist_delete"),
]
