# Generated by Django 5.1.4 on 2026-05-04 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0002_billingdocumentbranding_and_more'),
        ('domains', '0005_domaincontact_registrant_validation'),
        ('products', '0003_alter_package_options_package_card_badge_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('quoted', 'Quoted'), ('invoiced', 'Invoiced'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_carts', to='billing.invoice')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_carts', to='billing.quote')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortalCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_type', models.CharField(choices=[('hosting', 'Hosting / service'), ('domain_registration', 'Domain registration')], max_length=32)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('billing_period', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('annually', 'Annually')], max_length=20)),
                ('domain_name', models.CharField(blank=True, max_length=255)),
                ('registration_years', models.PositiveSmallIntegerField(default=1)),
                ('privacy_enabled', models.BooleanField(default=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('dns_provider', models.CharField(choices=[('registrar', 'Registrar'), ('cpanel', 'cPanel'), ('cloudflare', 'Cloudflare'), ('external', 'External')], default='cpanel', max_length=20)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='portal.portalcart')),
                ('domain_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_cart_items', to='domains.domaincontact')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_cart_items', to='products.package')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
