# Generated by Django 5.1.4 on 2026-05-04 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0006_domaintransfer'),
        ('portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='portalcart',
            name='created_by_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_carts_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='portalcartitem',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_cart_items', to='domains.domain'),
        ),
        migrations.AddField(
            model_name='portalcartitem',
            name='transfer_auth_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='portalcartitem',
            name='item_type',
            field=models.CharField(choices=[('hosting', 'Hosting / service'), ('domain_registration', 'Domain registration'), ('domain_renewal', 'Domain renewal'), ('domain_transfer', 'Domain transfer')], max_length=32),
        ),
    ]
