# Generated by Django 5.1.4 on 2026-05-04 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_promo_code_announcement_banner'),
        ('portal', '0002_portalcart_created_by_staff_portalcartitem_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalcart',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='core.promocode'),
        ),
    ]
