upstream django {
    server web:7000;
}

server {
    listen 780 default_server;
    server_name _;

    location /static/ {
        alias /app/staticfiles/;
    }

    location /media/support/ {
        return 403;
    }

    location /media/ {
        alias /app/media/;
    }

    location / {
        proxy_pass http://django;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }
}

include /etc/nginx/conf.d/sites/*.conf;
