# Generated by Django 5.1.4 on 2026-05-04 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAllowlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('label', models.CharField(blank=True, help_text="Friendly name, e.g. 'Office VPN'", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_allowlist_entries_added', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IP allowlist entry',
                'verbose_name_plural': 'IP allowlist entries',
                'ordering': ['ip_address'],
            },
        ),
    ]
