# Generated by Django 5.1.4 on 2026-05-05 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0001_initial'),
        ('services', '0002_service_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='WHMPackageSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('owner', models.CharField(blank=True, max_length=120)),
                ('feature_list', models.CharField(blank=True, max_length=120)),
                ('disk_quota_mb', models.CharField(blank=True, max_length=64)),
                ('bandwidth_quota_mb', models.CharField(blank=True, max_length=64)),
                ('max_email_accounts', models.CharField(blank=True, max_length=64)),
                ('max_ftp_accounts', models.CharField(blank=True, max_length=64)),
                ('max_databases', models.CharField(blank=True, max_length=64)),
                ('max_subdomains', models.CharField(blank=True, max_length=64)),
                ('max_parked_domains', models.CharField(blank=True, max_length=64)),
                ('max_addon_domains', models.CharField(blank=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WHMServerSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.CharField(max_length=255)),
                ('server_version', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-synced_at'],
            },
        ),
        migrations.CreateModel(
            name='WHMSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('package_count', models.PositiveIntegerField(default=0)),
                ('account_count', models.PositiveIntegerField(default=0)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('result_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WHMAccountSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=64, unique=True)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('owner', models.CharField(blank=True, max_length=120)),
                ('plan', models.CharField(blank=True, max_length=120)),
                ('ip', models.CharField(blank=True, max_length=64)),
                ('server', models.CharField(blank=True, max_length=255)),
                ('partition', models.CharField(blank=True, max_length=255)),
                ('unix_start_date', models.CharField(blank=True, max_length=120)),
                ('suspended', models.BooleanField(default=False)),
                ('suspended_reason', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whm_account_snapshots', to='services.service')),
            ],
            options={
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='WHMAccountUsageSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disk_used_mb', models.CharField(blank=True, max_length=64)),
                ('disk_limit_mb', models.CharField(blank=True, max_length=64)),
                ('disk_used_percent', models.CharField(blank=True, max_length=64)),
                ('inode_used', models.CharField(blank=True, max_length=64)),
                ('inode_limit', models.CharField(blank=True, max_length=64)),
                ('inode_used_percent', models.CharField(blank=True, max_length=64)),
                ('monthly_bandwidth_used_mb', models.CharField(blank=True, max_length=64)),
                ('monthly_bandwidth_limit_mb', models.CharField(blank=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='provisioning.whmaccountsnapshot')),
            ],
            options={
                'ordering': ['account__username'],
            },
        ),
    ]
