# Generated by Codex on 2026-05-29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("provisioning", "0002_whmpackagesnapshot_whmserversnapshot_whmsyncrun_and_more"),
        ("services", "0004_service_provisioning_provider_and_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="HostingNode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("hostname", models.CharField(max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("daemon_url", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("draining", "Draining"),
                            ("offline", "Offline"),
                            ("maintenance", "Maintenance"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("last_error", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Hosting node",
                "verbose_name_plural": "Hosting nodes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WebsiteRuntime",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "runtime_type",
                    models.CharField(
                        choices=[
                            ("static", "Static"),
                            ("php", "PHP"),
                            ("node", "Node.js"),
                            ("python", "Python"),
                            ("custom", "Custom"),
                        ],
                        default="static",
                        max_length=30,
                    ),
                ),
                ("image", models.CharField(max_length=255)),
                ("image_tag", models.CharField(default="latest", max_length=120)),
                ("document_root", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("failed", "Failed"),
                            ("retired", "Retired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("last_deployed_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="website_runtimes",
                        to="provisioning.hostingnode",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="website_runtimes",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Website runtime",
                "verbose_name_plural": "Website runtimes",
                "ordering": ["service", "runtime_type", "image"],
            },
        ),
        migrations.CreateModel(
            name="WebsiteContainer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("container_name", models.CharField(max_length=255, unique=True)),
                ("internal_port", models.PositiveIntegerField(default=80)),
                ("domain", models.CharField(max_length=255)),
                ("document_root", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("creating", "Creating"),
                            ("running", "Running"),
                            ("stopped", "Stopped"),
                            ("unhealthy", "Unhealthy"),
                            ("failed", "Failed"),
                            ("removed", "Removed"),
                        ],
                        default="creating",
                        max_length=20,
                    ),
                ),
                ("healthcheck_url", models.URLField(blank=True)),
                ("last_deployed_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="website_containers",
                        to="provisioning.hostingnode",
                    ),
                ),
                (
                    "runtime",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="containers",
                        to="provisioning.websiteruntime",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="website_containers",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Website container",
                "verbose_name_plural": "Website containers",
                "ordering": ["domain", "container_name"],
            },
        ),
        migrations.AddConstraint(
            model_name="websiteruntime",
            constraint=models.UniqueConstraint(
                fields=("service", "runtime_type", "image", "image_tag"),
                name="uniq_website_runtime_per_service_image",
            ),
        ),
        migrations.AddConstraint(
            model_name="websitecontainer",
            constraint=models.UniqueConstraint(
                fields=("node", "domain"),
                name="uniq_website_container_node_domain",
            ),
        ),
    ]
